"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import ExplorerMap, { GlobeOverlay } from "./ExplorerMap"

export default function CityExplorer() {
  const [mounted, setMounted] = useState(false)
  const [panelOpen, setPanelOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")
  const [wellbeingScore, setWellbeingScore] = useState(78)

  const [overlays, setOverlays] = useState<GlobeOverlay[]>([
    { id: "vegetation", name: "Vegetation", icon: "🌱", color: "#22c55e", active: false },
    { id: "heat", name: "Urban Heat Islands", icon: "☀️", color: "#ef4444", active: false },
    { id: "air", name: "Air Quality", icon: "🌬️", color: "#ef4444", active: false },
    { id: "water", name: "Water Quality", icon: "💧", color: "#3b82f6", active: false },
    { id: "agriculture", name: "Agriculture Suitability Zones", icon: "⚡", color: "#f59e0b", active: false },
  ])

  useEffect(() => {
    setMounted(true)
  }, [])

  const toggleOverlay = (id: string) => {
    setOverlays((prev) => {
      const newOverlays = prev.map((o) => (o.id === id ? { ...o, active: !o.active } : o))
      updateWellbeingScore(newOverlays)
      return newOverlays
    })
    setTimeout(() => setPanelOpen(false), 300)
  }

  const updateWellbeingScore = (currentOverlays: GlobeOverlay[]) => {
    // Simple logic: each active overlay contributes +5 to base 70 score
    let score = 70
    currentOverlays.forEach((o) => {
      if (o.active) score += 5
    })
    if (score > 100) score = 100
    setWellbeingScore(score)
  }

  const searchCity = () => {
    if (!searchQuery.trim()) return
    alert(`Searching for city: ${searchQuery}`)
    // Reset overlays when searching new city
    const resetOverlays = overlays.map((o) => ({ ...o, active: false }))
    setOverlays(resetOverlays)
    setWellbeingScore(78) // default for new city
  }

  const handleSearchKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") searchCity()
  }

  const generateReport = () => {
    const reportContent = `
EXONOVA City Health Suggestion Report - ${searchQuery || "Current Location"}

Overall Wellbeing Score: ${wellbeingScore}/100

Active Data Layers:
${overlays.filter((o) => o.active).map((o) => `- ${o.name}`).join("\n") || "- None"}

Suggestions:
- Increase green spaces in urban heat island zones
- Improve air quality monitoring systems
- Enhance water treatment facilities
- Develop sustainable agriculture zones

Generated by EXONOVA City Health Explorer
`

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const newWindow = window.open()
    if (newWindow) {
      newWindow.document.write(`
<html>
<head><title>EXONOVA Report</title></head>
<body style="font-family: monospace; background: black; color: white; padding: 20px;">
<pre style="color:white;">${reportContent}</pre>
<br>
<a href="${url}" download="exonova-report.txt" style="color: #3b53f9; text-decoration: none; border: 1px solid #3b53f9; padding: 10px; display: inline-block;">Download Report</a>
</body>
</html>
      `)
    }
    setPanelOpen(false)
  }

  if (!mounted) return null

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      {/* Starfield Background */}
      <div className="absolute inset-0 z-0">
        <div className="stars"></div>
        <div className="stars2"></div>
        <div className="stars3"></div>
      </div>

      {/* Search Bar */}
      <div className="fixed top-20 right-6 z-50">
        <div className="flex items-center bg-white rounded-lg px-4 py-2 border border-gray-300 shadow-md">
          <input
            type="text"
            placeholder="Search for a city..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onKeyPress={handleSearchKeyPress}
            className="bg-white text-black placeholder-gray-500 outline-none w-64"
          />
          <button onClick={searchCity} className="ml-2 text-black hover:text-[#3b53f9] transition-colors">
            🔍
          </button>
        </div>
      </div>

      {/* Explore City Health Button */}
      {!panelOpen && (
        <div className="fixed top-20 left-6 z-50">
          <button
            onClick={() => setPanelOpen(true)}
            className="bg-gradient-to-r from-[#3b53f9] to-[#3b53f9] text-black px-6 py-3 rounded-lg font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
          >
            Explore City Health
          </button>
        </div>
      )}

      {/* Left Panel */}
      <div
        className={`fixed left-0 top-20 bottom-0 w-80 bg-black/80 backdrop-blur-md border-r border-[#3b53f9]/30 transform transition-transform duration-500 z-40 ${
          panelOpen ? "translate-x-0" : "-translate-x-full"
        }`}
        style={{
          background: "linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(59,83,249,0.1) 100%)",
          boxShadow: "0 0 30px rgba(59,83,249,0.3), inset 0 0 30px rgba(59,83,249,0.1)",
        }}
      >
        <div className="flex flex-col h-full p-6 border border-[#3b53f9]/20 rounded-r-lg">
          <h2 className="text-xl font-bold text-[#3b53f9] mb-6">City Health Analysis</h2>
          <div className="flex-1 overflow-y-auto pr-2">
            <style>{`
              ::-webkit-scrollbar { width: 6px; }
              ::-webkit-scrollbar-track { background: rgba(0,0,0,0.2); }
              ::-webkit-scrollbar-thumb { background-color: white; border-radius: 3px; }
            `}</style>

            {/* Overlay Controls */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4 text-[#3b53f9]">Data Overlays</h3>
              <div className="space-y-3">
                {overlays.map((overlay) => (
                  <button
                    key={overlay.id}
                    onClick={() => toggleOverlay(overlay.id)}
                    className={`w-full flex items-center space-x-3 p-3 rounded border transition-all ${
                      overlay.active
                        ? "border-[#3b53f9] bg-[#3b53f9]/10 shadow-[0_0_10px_#3b53f9] text-white"
                        : "border-white/20 bg-gray-800 text-white hover:border-[#3b53f9]/50 hover:bg-gray-700"
                    }`}
                  >
                    <span className="text-xl">{overlay.icon}</span>
                    <span className="text-sm">{overlay.name}</span>
                    {overlay.active && <div className="ml-auto w-2 h-2 rounded-full animate-pulse" style={{ backgroundColor: overlay.color }} />}
                  </button>
                ))}
              </div>
            </div>

            {/* Wellbeing Score */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4 text-[#3b53f9]">City Wellbeing Score</h3>
              <div className="relative w-32 h-32 mx-auto">
                <svg className="w-32 h-32 transform -rotate-90" viewBox="0 0 120 120">
                  <circle cx="60" cy="60" r="50" fill="none" stroke="white" strokeWidth="8" />
                  <circle
                    cx="60"
                    cy="60"
                    r="50"
                    fill="none"
                    stroke="white"
                    strokeWidth="8"
                    strokeLinecap="round"
                    strokeDasharray={`${(wellbeingScore / 100) * 314} 314`}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="text-2xl font-bold text-white">{wellbeingScore}</span>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-4 flex-shrink-0">
            <Button
              onClick={generateReport}
              className="w-full bg-gradient-to-r from-[#3b53f9] to-[#3b53f9] text-white font-semibold py-3 rounded-lg transition-all duration-300 shadow-lg hover:shadow-xl"
            >
              Generate Suggestion Report
            </Button>
          </div>
        </div>
      </div>

      {/* Explorer Map */}
      <ExplorerMap overlays={overlays} />
    </div>
  )
}
