"use client"

import type React from "react"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"

interface GlobeOverlay {
  id: string
  name: string
  icon: string
  color: string
  active: boolean
}

export default function CityExplorer() {
  const [mounted, setMounted] = useState(false)
  const [panelOpen, setPanelOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")
  const [wellbeingScore, setWellbeingScore] = useState(78)
  const cesiumContainerRef = useRef<HTMLDivElement>(null)
  const viewerRef = useRef<any>(null)

  const [overlays, setOverlays] = useState<GlobeOverlay[]>([
    { id: "vegetation", name: "Vegetation", icon: "🌱", color: "#22c55e", active: false },
    { id: "heat", name: "Urban Heat Islands", icon: "☀️", color: "#ef4444", active: false },
    { id: "air", name: "Air Quality", icon: "🌬️", color: "#06b6d4", active: false },
    { id: "water", name: "Water Quality", icon: "💧", color: "#3b82f6", active: false },
    { id: "agriculture", name: "Agriculture Suitability Zones", icon: "⚡", color: "#f59e0b", active: false },
  ])

  useEffect(() => {
    setMounted(true)
    initializeCesium()
  }, [])

  const initializeCesium = async () => {
    if (typeof window !== "undefined" && cesiumContainerRef.current) {
      try {
        const { Viewer, Terrain, createWorldTerrain, Ion } = await import("cesium")

        Ion.defaultAccessToken =
          "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkMmEyZjIwMS1hMGIzLTRmNWQtODdiYy02NjY5OTI3NWRjMTAiLCJpZCI6MzQzMjkwLCJpYXQiOjE3NTg0NTkwODd9.TpC7YS6AYs0_8KCBT0CMJq8m4ELfWQ9bgUXXrkCX6Lg"

        const viewer = new Viewer(cesiumContainerRef.current, {
          terrain: createWorldTerrain(),
          homeButton: false,
          sceneModePicker: false,
          baseLayerPicker: false,
          navigationHelpButton: false,
          animation: false,
          timeline: false,
          fullscreenButton: false,
          vrButton: false,
          geocoder: false,
          infoBox: false,
          selectionIndicator: false,
          shadows: true,
          terrainShadows: 2,
          requestRenderMode: true,
          maximumRenderTimeChange: Number.POSITIVE_INFINITY,
        })

        viewer.scene.backgroundColor = new (await import("cesium")).Color(0, 0, 0, 1)
        viewer.scene.globe.baseColor = new (await import("cesium")).Color(0.1, 0.1, 0.2, 1)

        viewerRef.current = viewer

        // Set initial view to Earth
        viewer.camera.setView({
          destination: new (await import("cesium")).Cartesian3.fromDegrees(0, 0, 20000000),
        })
      } catch (error) {
        console.error("Failed to initialize Cesium:", error)
      }
    }
  }

  const searchCity = async () => {
    if (!searchQuery.trim() || !viewerRef.current) return

    try {
      const response = await fetch(
        `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(searchQuery)}`,
      )
      const results = await response.json()

      if (results.length > 0) {
        const { lat, lon } = results[0]
        const { Cartesian3 } = await import("cesium")

        viewerRef.current.camera.flyTo({
          destination: Cartesian3.fromDegrees(Number.parseFloat(lon), Number.parseFloat(lat), 1000000),
          duration: 3.0,
        })

        // Update wellbeing score based on city (mock data)
        setWellbeingScore(Math.floor(Math.random() * 40) + 60)
      }
    } catch (error) {
      console.error("Search failed:", error)
    }
  }

  const handleSearchKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      searchCity()
    }
  }

  const toggleOverlay = (id: string) => {
    setOverlays((prev) =>
      prev.map((overlay) => (overlay.id === id ? { ...overlay, active: !overlay.active } : overlay)),
    )
    setTimeout(() => setPanelOpen(false), 300)
  }

  const generateReport = () => {
    const reportContent = `
      EXONOVA City Health Report - ${searchQuery || "Current Location"}
      
      Overall Wellbeing Score: ${wellbeingScore}/100
      
      Active Data Layers:
      ${overlays
        .filter((o) => o.active)
        .map((o) => `- ${o.name}`)
        .join("\n      ")}
      
      Recommendations:
      - Increase green spaces in urban heat island zones
      - Improve air quality monitoring systems
      - Enhance water treatment facilities
      - Develop sustainable agriculture zones
      
      Generated by EXONOVA City Health Explorer
    `

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const newWindow = window.open()
    if (newWindow) {
      newWindow.document.write(`
        <html>
          <head><title>EXONOVA Report - ${searchQuery || "Current Location"}</title></head>
          <body style="font-family: monospace; background: #000; color: #00F0FF; padding: 20px;">
            <pre>${reportContent}</pre>
            <br>
            <a href="${url}" download="exonova-report-${(searchQuery || "location").toLowerCase()}.txt" 
               style="color: #00F0FF; text-decoration: none; border: 1px solid #00F0FF; padding: 10px; display: inline-block;">
              Download Report
            </a>
          </body>
        </html>
      `)
    }
    setPanelOpen(false)
  }

  if (!mounted) return null

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      {/* Starfield Background */}
      <div className="absolute inset-0 z-0">
        <div className="stars"></div>
        <div className="stars2"></div>
        <div className="stars3"></div>
      </div>

      <div className="absolute top-6 right-6 z-50 flex items-center space-x-3">
        <div className="flex items-center bg-black/80 backdrop-blur-md border border-[#00F0FF]/30 rounded-lg px-4 py-2 flex-col       type="text"
            placeholder="Search for a city..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onKeyPress={handleSearchKeyPress}
            className="bg-transparent text-white placeholder-white/50 outline-none w-64 h-0"
          />
          <button onClick={searchCity} className="ml-2 text-[#00F0FF] hover:text-white transition-colors">
            🔍
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="relative z-20 pt-20 h-screen flex">
        {/* Left Panel - Slides in when opened */}
        <div
          className={`fixed left-0 top-20 bottom-0 w-80 bg-black/80 backdrop-blur-md border-r border-[#00F0FF]/30 transform transition-transform duration-500 z-40 ${
            panelOpen ? "translate-x-0" : "-translate-x-full"
          }`}
          style={{
            background: "linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(0,240,255,0.1) 100%)",
            boxShadow: "0 0 30px rgba(0,240,255,0.3), inset 0 0 30px rgba(0,240,255,0.1)",
          }}
        >
          <div className="p-6 h-full flex flex-col border border-[#00F0FF]/20 rounded-r-lg">
            <h2 className="text-xl font-bold text-[#00F0FF] mb-6">City Health Analysis</h2>

            {/* Overlay Controls */}
            <div className="mb-6 flex-1">
              <h3 className="text-lg font-semibold mb-4 text-[#9B59FF]">Data Overlays</h3>
              <div className="space-y-3">
                {overlays.map((overlay) => (
                  <button
                    key={overlay.id}
                    onClick={() => toggleOverlay(overlay.id)}
                    className={`w-full flex items-center space-x-3 p-3 rounded border transition-all ${
                      overlay.active
                        ? "border-[#00F0FF] bg-[#00F0FF]/10 shadow-[0_0_10px_#00F0FF]"
                        : "border-white/20 bg-black/30 hover:border-[#00F0FF]/50"
                    }`}
                  >
                    <span className="text-xl">{overlay.icon}</span>
                    <span className="text-sm">{overlay.name}</span>
                    {overlay.active && (
                      <div
                        className="ml-auto w-2 h-2 rounded-full animate-pulse"
                        style={{ backgroundColor: overlay.color }}
                      ></div>
                    )}
                  </button>
                ))}
              </div>
            </div>

            {/* Wellbeing Score */}
            <div className="mb-6">
              <h3 className="text-lg font-semibold mb-4 text-[#9B59FF]">City Wellbeing Score</h3>
              <div className="relative w-32 h-32 mx-auto">
                <svg className="w-32 h-32 transform -rotate-90" viewBox="0 0 120 120">
                  <circle cx="60" cy="60" r="50" fill="none" stroke="rgba(0, 240, 255, 0.2)" strokeWidth="8" />
                  <circle
                    cx="60"
                    cy="60"
                    r="50"
                    fill="none"
                    stroke="#00F0FF"
                    strokeWidth="8"
                    strokeLinecap="round"
                    strokeDasharray={`${(wellbeingScore / 100) * 314} 314`}
                    className="animate-pulse"
                    style={{ filter: "drop-shadow(0 0 10px #00F0FF)" }}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="text-2xl font-bold neon-cyan">{wellbeingScore}</span>
                </div>
              </div>
            </div>

            {/* Generate Report Button */}
            <Button
              onClick={generateReport}
              className="w-full bg-gradient-to-r from-[#00F0FF] to-[#0891b2] hover:from-[#00F0FF]/90 hover:to-[#0891b2]/90 text-black font-semibold py-3 rounded-lg transition-all duration-300 shadow-lg hover:shadow-xl"
            >
              Generate Suggestion Report
            </Button>
          </div>
        </div>

        {/* Globe Container */}
        <div className="flex-1 relative">
          {!panelOpen && (
            <div className="absolute top-6 left-6 z-50">
              <button
                onClick={() => setPanelOpen(true)}
                className="bg-gradient-to-r from-[#00F0FF] to-[#0891b2] text-black px-6 py-3 rounded-lg font-semibold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
              >
                Explore City Health
              </button>
            </div>
          )}

          <div ref={cesiumContainerRef} className="flex items-center bg-black/80 backdrop-blur-md border border-[#00F0FF]/30 rounded-lg px-4 py-2 flex-colt text-white placeholder-white/50 outline-none w-64 mb-3" style={{ background: "black" }} />
        </div>
      </div>

      {/* Holographic Grid Overlay */}
      <div className="absolute inset-0 z-10 opacity-10">
        <div className="grid-overlay"></div>
      </div>
    </div>
  )
}
